### ISSUE TITLE
How to authenticate docker? 

### ISSUE THREAD

**Issue by thewismit** [pawelmalak/snippet-box#11]
I'm getting an error authenticating. I've tried running docker login and authenticating prior to using docker run. 

I can't seem to find the right syntax from Google either. Mind correcting me? Thanks. 

Unable to find image 'snippet-box:arm' locally
docker: Error response from daemon: pull access denied for snippet-box, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'

**Comment by pawelmalak** [comment]
Can you show the entire command that you tried to run? Have you built your image locally or are you trying to pull it from docker hub?

**Comment by thewismit** [comment]
Thank you for replying :) I've tried both

docker buildx build   --platform linux/arm/v7,linux/arm64   -f Dockerfile.arm   -t snippet-box:arm

Returns

error: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

And

docker run -p 5000:5000 -v /home/user/docker/volumes/snippet-box:/app/data snippet-box:arm

Returns

Unable to find image 'snippet-box:arm' locally
docker: Error response from daemon: pull access denied for snippet-box, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by pawelmalak** [comment]
For the first command you need to add . at the end. So it will be:
```bash
docker buildx build --platform linux/arm/v7,linux/arm64 -f Dockerfile.arm -t snippet-box:arm .
```
I will update README file with correct syntax. 

As for the second command. You are trying to create container from the local image. Because it's not there it tried to find it at your docker hub repository. That's why it asked for your credentials. If you want to use my prebuilt image you need to use:
```bash
docker run -p 5000:5000 -v /home/user/docker/volumes/snippet-box:/app/data pawelmalak/snippet-box:arm
```

**Comment by thewismit** [comment]
Thank you for the help. I will give this a try later on today!
