### ISSUE TITLE
Feature Request: String search function

### ISSUE THREAD

**Issue by OldStarFox** [pawelmalak/snippet-box#18]
It would be nice to have a search bar to perform string searches. If possible add options to search on description, tags and command. I know we can filter by tag but as the snippet library grows, I can see finding what you want may become cumbersome, specially if you did not tag your snippets properly.

I have been using this extensively and I appreciate all the work.

**Comment by pawelmalak** [comment]
I already have it on my todo list just wanted to implement tags first.

**Comment by OldStarFox** [comment]
No rush! Thanks for the reply and awesome work.

**Comment by pawelmalak** [comment]
Implemented. Please visit wiki for reference: [Search functionality](https://github.com/pawelmalak/snippet-box/wiki/Search-functionality)
