### ISSUE TITLE
Add support for Raspberry Pi

### ISSUE THREAD

**Issue by afonsosantos** [pawelmalak/snippet-box#2]
Hi! Just found this project via Reddit, and that's something I've been looking for some time now.

I would want to run this in my Raspberry Pi 4 at home, but as the CPU type is different, this project is not yet supported.
Can you take a look at what would be required for this project to run on the ARM CPU? I would be willing to make a PR with the changes required and test it on my device.

Below the error message:

```bash
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
```

Thank you!

**Comment by pawelmalak** [comment]
I created new image for arm devices. You can pull it from `pawelmalak/snippet-box:arm`. Tested it on my RPi 4B with 64bit OS.

**Comment by afonsosantos** [comment]
Thank you! I can confirm that's working now.
