### ISSUE TITLE
Wrong date / time on fresh install, pull

### ISSUE THREAD

**Issue by mccount** [pawelmalak/snippet-box#22]
![grafik](https://user-images.githubusercontent.com/7852259/136856377-317025d0-aa0b-4503-8168-4863ccac6d1d.png)

**Comment by pawelmalak** [comment]
That's weird. I created two new instances using both tags and it's working fine.
What browser are you using and on what platform?

**Comment by Starf0x** [comment]
I have both, the internal version has the correct date and time, the one external (nginx) version shows indeed NaN.

**Comment by pawelmalak** [comment]
> I have both, the internal version has the correct date and time, the one external (nginx) version shows indeed NaN.

What browser and platform?

I have three instances of snippet box running:
- local only - using `latest` tag
- local only - using `arm` tag
- behind nginx reverse proxy - using `latest` tag

and I'm getting correct dates on all of them so it might be related to browser you are using.

**Comment by firstchrono** [comment]
I'm seeing this issue. I'm using the local only `latest` tag and the browser is FF 93. 

It does appear to be browser related. If I switch to chrome, it works fine.

**Comment by pawelmalak** [comment]
So it seems that it works on chromium based browsers (tested on Chrome, Opera and Edge) but gives `NaN` on Firefox and Safari. I will try to fix it when I have a moment.

**Comment by mccount** [comment]
Web development at it's best. I can confirm this is Firefox related only. (no access to safari)
Thanks for your effort @pawelmalak, take your time!
