### ISSUE TITLE
Feature Request: Basic Version Control

### ISSUE THREAD

**Issue by BadCo-NZ** [pawelmalak/snippet-box#24]
Hi, Snippet-Box looks like a great alternative to self-hosting a git repo for managing my docker compose files. However, it is missing versioning or version control.

I have no idea how this could be implemented, but it could be as simple as adding a "Version" field in the editor? This would mean multiple snippets for one compose file though.

Great work so far on Snippet-Box and Flame! :+1: :+1: :+1:

**Comment by pawelmalak** [comment]
You mean like edit history within the app?

**Comment by BadCo-NZ** [comment]
> You mean like edit history within the app?

Yeah, something along those lines.

So if I make a breaking change in a compose file, I can roll back to the last working version.

**Comment by BadCo-NZ** [comment]
I have moved to a self hosted git repo, Gitea!
