### ISSUE TITLE
Feature Request: Code Formatting

### ISSUE THREAD

**Issue by MJWherry** [pawelmalak/snippet-box#28]
Add code formatting based on possible languages (C#, python, etc)

**Comment by pawelmalak** [comment]
Do you know any node.js libraries that support code formatting for multiple languages? I was only able to find formatters for html, css, json and js.

**Comment by Torqu3Wr3nch** [comment]
Would like to second this request- it's basically the only thing holding me back from using snippet-box. 

@pawelmalak Not a node guy, but maybe [highlight.js](https://highlightjs.org/)?

From https://highlightjs.org/download/:

> Node.js
> Highlight.js can be used on the server through the API. The package with all supported languages is installable from NPM:
> 
> `npm install highlight.js`

By the way, great work!

**Comment by pawelmalak** [comment]
Snippet-box is already using highlight.js for, well, syntax highlighting. Afaik, it doesn't have option to format your code.

**Comment by JaneMillor** [comment]
Is there a list of supported code syntax /code formatting ? would love to see support of yaml, a example of a online syntax for yaml would be yamlchecker dot com

Would also be great to have line numbers in the code examples :-)
